### PR TITLE
On the fly analysis, raster tile sets, better support for different geometry types

### PR DESCRIPTION
**Pull request by thomas-maschler**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: 
- [GTC-553]
- [GTC-38]
- [GTC-832]
- [GTC-792]
- [GTC-707]

## What is the new behavior?

- On the Fly Analysis
- Raster tile sets
- Better support for different geometry types
- Terminate long running SQL queries of API GET requests DB site
- Force WM geometries to be always 2d
- Fix 500 error when creating version for wrong dataset
- Fix bug, which requires to always list metadata property when creating a version
- Allow to create Geo Packages

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

[GTC-553]: https://gfw.atlassian.net/browse/GTC-553
[GTC-38]: https://gfw.atlassian.net/browse/GTC-38
[GTC-832]: https://gfw.atlassian.net/browse/GTC-832
[GTC-792]: https://gfw.atlassian.net/browse/GTC-792
[GTC-707]: https://gfw.atlassian.net/browse/GTC-707

### CODE REVIEW

**Comment by thomas-maschler** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Coverage increased per file
===========================
+ app/main.py  1
+ app/errors.py  13
+ app/routes/datasets/queries.py  5
+ app/utils/rw_api.py  18
         

Complexity increasing per file
==============================
- app/models/enum/analysis.py  1
- app/routes/analysis/analysis.py  2
- app/models/pydantic/analysis.py  1
- app/utils/geostore.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wri/gfw-data-api/pullRequest?prid=6348554&bid=20617993)

**Comment by thomas-maschler** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- app/routes/assets/assets.py  1
- app/models/enum/analysis.py  1
- app/models/enum/pixetl.py  1
- app/models/pydantic/analysis.py  1
- app/routes/analysis/analysis.py  2
- app/utils/geostore.py  4
- app/routes/datasets/__init__.py  1
- app/tasks/raster_tile_set_assets.py  8
         

Clones added
============
- app/routes/assets/assets.py  1
- app/routes/datasets/asset.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wri/gfw-data-api/pullRequest?prid=6348554&bid=20617993)

**Comment by thomas-maschler** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- app/routes/datasets/__init__.py  1
- app/tasks/raster_tile_set_assets.py  8
- app/routes/analysis/analysis.py  2
- app/models/enum/analysis.py  1
- app/routes/assets/assets.py  1
- app/utils/geostore.py  4
- app/models/enum/pixetl.py  1
- app/models/pydantic/analysis.py  1
         

Clones added
============
- app/routes/datasets/asset.py  1
- app/routes/assets/assets.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wri/gfw-data-api/pullRequest?prid=6348554&bid=20617993)

**Comment by thomas-maschler** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- app/crud/versions.py  1
- app/models/enum/pixetl.py  1
- app/routes/datasets/__init__.py  1
- app/routes/assets/assets.py  1
- app/utils/geostore.py  4
- app/models/enum/analysis.py  1
- app/routes/analysis/analysis.py  2
- app/tasks/static_vector_file_assets.py  2
- app/tasks/raster_tile_set_assets.py  8
- app/models/pydantic/analysis.py  1
         

Clones added
============
- app/routes/datasets/asset.py  1
- app/routes/assets/assets.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wri/gfw-data-api/pullRequest?prid=6348554&bid=20617993)

**Comment by thomas-maschler** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- app/utils/geostore.py  4
- app/crud/versions.py  1
- app/models/enum/pixetl.py  1
- app/routes/assets/assets.py  1
- app/tasks/raster_tile_set_assets.py  9
- app/routes/analysis/analysis.py  2
- app/tasks/static_vector_file_assets.py  2
- app/models/pydantic/analysis.py  1
- app/models/enum/analysis.py  1
- app/routes/datasets/__init__.py  1
         

Clones added
============
- app/routes/assets/assets.py  1
- app/routes/datasets/asset.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wri/gfw-data-api/pullRequest?prid=6348554&bid=20617993)

**Comment by thomas-maschler** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- app/utils/geostore.py  4
- app/models/pydantic/analysis.py  1
- app/routes/datasets/__init__.py  1
- app/routes/assets/assets.py  1
- app/tasks/static_vector_file_assets.py  2
- app/models/enum/analysis.py  1
- app/tasks/raster_tile_set_assets.py  9
- app/crud/versions.py  1
- app/models/enum/pixetl.py  1
- app/routes/analysis/analysis.py  2
         

Clones added
============
- app/routes/datasets/asset.py  1
- app/routes/assets/assets.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wri/gfw-data-api/pullRequest?prid=6348554&bid=20617993)

**Review by dmannarino — APPROVED** [review]

**Pull request merged**
