### PR TITLE
cancel query server side if it runs for too long

### PR DESCRIPTION
**Pull request by thomas-maschler**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [X] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [X] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

- Query returns Internal Server error when wrong Column name used
- Request times out when running longer than 1 min, but query continues to run on server, possibly jamming other requests

## What is the new behavior?

- Catch `UndefinedColumnError` 
- Cancel long running queries server side and respond with `524`

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by thomas-maschler** [comment]
Ideally I'd like to set this already at the `db` level but somehow gino doesn't except this argument. I opened a ticket
https://github.com/python-gino/gino/issues/725

**Comment by thomas-maschler** [comment]
@jterry64 
I get 
```
=================================== FAILURES ===================================
______________________ test_raster_analysis__lambda_error ______________________

async_client = <httpx._client.AsyncClient object at 0x7f5f4c4a47c0>
lambda_client = <function lambda_client.<locals>.create_lambda at 0x7f5f4f2259d0>

    @pytest.mark.asyncio
    async def test_raster_analysis__lambda_error(async_client, lambda_client):
        """Basic test to check if empty data api response as expected."""
        lambda_client(FAIL_FUNC_STR)
    
        with pytest.raises(InvalidResponseError):
>           await async_client.get(
                f"/analysis/zonal/{SAMPLE_GEOSTORE_ID}?geostore_origin=rw&group_by=umd_tree_cover_loss__year"
            )
E           Failed: DID NOT RAISE <class 'app.errors.InvalidResponseError'>

tests/routes/test_analysis.py:49: Failed
```
But I did not touch any of that code. Any clue why this happens?

**Review by dmannarino — APPROVED** [review]

**Comment by thomas-maschler** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wri/gfw-data-api/pullRequest?prid=6214634&bid=20263422)

**Comment by thomas-maschler** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wri/gfw-data-api/pullRequest?prid=6214634&bid=20263422)

**Comment by thomas-maschler** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wri/gfw-data-api/pullRequest?prid=6214634&bid=20263422)

**Pull request merged**
