### PR TITLE
Feature/viirs metadata

### PR DESCRIPTION
**Pull request by solomon-negusse**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: [GTC-2390](https://gfw.atlassian.net/browse/GTC-2390)
Data-pump updates don't have a way set content_date_range when appending data

## What is the new behavior?

- Add ability to update metadata when appending

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

[GTC-2390]: https://gfw.atlassian.net/browse/GTC-2390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jterry64 — APPROVED** [review]
Didn't even think about that, looks good to me! I guess alternatively the data API could just directly PATCH the metadata after appending. The only case I can see where that's better is if the append task fails, the content date range would already be updated, so clients like flagship would think there's new data when there isn't. @solomon-negusse @dmannarino what do you think?

**Review by dmannarino — APPROVED** [review]

**Comment by solomon-negusse** [comment]
> Didn't even think about that, looks good to me! I guess alternatively the data API could just directly PATCH the metadata after appending. The only case I can see where that's better is if the append task fails, the content date range would already be updated, so clients like flagship would think there's new data when there isn't. @solomon-negusse @dmannarino what do you think?

I actually started out implementing that but without persisting the metadata payload, don't see a way of passing that to where jobs statuses are [checked](https://github.com/wri/gfw-data-api/blob/master/app/routes/tasks/task.py#L190) and updated. I resorted to this way as the version status will be set to failed if append fails anyway (so client shouldn't rely on the content date range). That will need manual intervention to revert to valid content date range and not too happy about the solution.
Does data-pump check if an append succeeds? In that case, can explore sending the `PATCH` request from data-pump on append success. I'm assuming moving the content end date around would be easier in data-pump than in Data API but need to validate that.

**Comment by dmannarino** [comment]
> Didn't even think about that, looks good to me! I guess alternatively the data API could just directly PATCH the metadata after appending. The only case I can see where that's better is if the append task fails, the content date range would already be updated, so clients like flagship would think there's new data when there isn't. @solomon-negusse @dmannarino what do you think?

Hmm, that's a good point. TBH I favor PATCHing the metadata after the append succeeds, like is done with the metadata and is_latest for the deforestation alerts. But I wouldn't object to this.

**Comment by solomon-negusse** [comment]
> > Didn't even think about that, looks good to me! I guess alternatively the data API could just directly PATCH the metadata after appending. The only case I can see where that's better is if the append task fails, the content date range would already be updated, so clients like flagship would think there's new data when there isn't. @solomon-negusse @dmannarino what do you think?
> 
> I actually started out implementing that but without persisting the metadata payload, don't see a way of passing that to where jobs statuses are [checked](https://github.com/wri/gfw-data-api/blob/master/app/routes/tasks/task.py#L190) and updated. I resorted to this way as the version status will be set to failed if append fails anyway (so client shouldn't rely on the content date range). That will need manual intervention to revert to valid content date range and not too happy about the solution. Does data-pump check if an append succeeds? In that case, can explore sending the `PATCH` request from data-pump on append success. I'm assuming moving the content end date around would be easier in data-pump than in Data API but need to validate that.

Turns out data-pump does check if append succeds, so I'm sending the PATCH request from that side so reverts the relevant changes here.

**Pull request merged**
